### ISSUE TITLE
defocus values for template

### ISSUE THREAD

**Issue by DrJesseHansen** [SBC-Utrecht/pytom-template-matching-gpu#48]
hi,

thanks again for the wonderful program.  It's a life saver!   

I have two questions about the template generation.

1) the template will be ctf corrected using the provided defocus.  I take it that defocus should match the tomogram?  Therefore I need to group my tomograms into defocus groups and generate a different template for each.   It's not a problem, just want to be sure I am correct.  I could not find anything about this in the manuscript, though I may have missed it.

2) I am unclear on the template contrast.  My input model is an mrc (white = signal) while the tomogram is inverted (black = signal). I am not sure whether to include the "invert" flag.  The note "WARNING not needed if ctf with defocus is already applied!" is a bit confusing.    

I used the command below:
pytom_create_template.py  -i act_htt_bin2_job007_B1000_12.9A.mrc -o template.mrc --input-voxel-size-angstrom 2.762 --output-voxel-size-angstrom 11.048 --center -c -z 5 -a 0.07 -v 300 --Cs 2.7 --cut-after-first-zero  

the output volume was black, so I guess I did the right thing by not including --invert.  I just want to be sure I am doing this correctly before proceeding.

**Comment by McHaillet** [comment]
Hi!

> the template will be ctf corrected using the provided defocus. I take it that defocus should match the tomogram? Therefore I need to group my tomograms into defocus groups and generate a different template for each. It's not a problem, just want to be sure I am correct. I could not find anything about this in the manuscript, though I may have missed it.

It depends on how much variation there is between tilt-series. Performance should improve if you take the defocus per tomograms, but performance might already be good enough with a rough defocus estimate for all tilt-series. For the data in the paper, it worked fine for me to convolute the tomogram with a single defocus for all the tilt-series that I matched in (likely also because its large ribosomes). But I expect performance improves with a defocus per groups of tilt-series with similar defocus.

> I am unclear on the template contrast. My input model is an mrc (white = signal) while the tomogram is inverted (black = signal). I am not sure whether to include the "invert" flag. The note "WARNING not needed if ctf with defocus is already applied!" is a bit confusing.

Hmm, the warning is indeed a little unclear. Basically a white template structure (as an electrostatic potential model should be) will turn black when convoluted with a CTF with defocus, while it will remain white when convoluted with a CTF with overfocus. Same as what you expect under a microscope. The --invert flag is there to give some more flexibility, in case you want to not convolute the template with a CTF and just want to get dark contrast, or have a subtomogram average that is black.

If your initial structure is white, you did the right thing indeed!

**Comment by McHaillet** [comment]
To solve this issue info logging to the user needs improvement

**Comment by McHaillet** [comment]
The warning for contrast inversion was removed a while back. Also the wiki contains more info now about template generation.
