### ISSUE TITLE
error message of the unittests

### ISSUE THREAD

**Issue by YunjieChang** [SBC-Utrecht/pytom-template-matching-gpu#58]
Hi there,

I am trying to install and test pytom-template matching on my own workstation, with unbuntu 22.04, nvidia 4090 and cuda 12.2.

No error message during the installation. However, I got the following error message (see the attached snapshot) for the unittests. Anyone know how to fix the issue?

Thanks in advance!
Yunjie
![Screenshot from 2023-11-03 22-00-21](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/54540487/2f55532c-34b7-4a17-b619-c304183523c7)

**Comment by McHaillet** [comment]
As a first check, could you run the following?

`python -c "from importlib.metadata import version; print(version('pytom-template-matching-gpu'))"`

If its not version '0.3.1', could you first try updating to the latest github version and see if the errors persist?

**Comment by YunjieChang** [comment]
Hi McHaillet,

I just updated pytom to 0.3.1, but got a similar error for the unittests (see attached snapshot). May u help check this?

Thanks!
Yunjie
![Screenshot from 2023-11-04 10-15-37](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/54540487/0af77e06-4c6e-4968-b466-5c91d4000892)

**Comment by McHaillet** [comment]
Hmm, not super clear to me what is going wrong in this test. I suspect it's not a critical issue, but rather a small nunerical inconsistency. Definitely needs to be solved. Thanks for reporting it and will get back to you about a solution.

As all other tests pass, the software is fuctioning correctly. So, you can safely use it.

**Comment by YunjieChang** [comment]
Thanks! Will let u know if I got any issues later.

**Comment by McHaillet** [comment]
Though it might be a difference with python=3.12 instead of the 3.11 that I tested with, but that is not the case.

My CUDA version is 12.2, and on our cluster where we have CUDA 11.8 it also works fine for me. So I guess its not a CUDA difference.

I do get the same warning from tqdm on 3.12 that issue #59 also reported, and that is likely related to the new python version.

```
/home/marten/miniconda3/envs/pytom_tm_12/lib/python3.12/site-packages/tqdm/std.py:580: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  if rate and total else datetime.utcfromtimestamp(0))
```

**Comment by McHaillet** [comment]
I think I understand the possible source of this failing test. It might just not be consistent, and the easiest solution would be to remove the test assertion on [line 213 in test_tmjob.py](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/blob/5dbc519204d834560fde83b509566326f9093c28/tests/test_tmjob.py#L213). Will explain why below.

Let's say we have a pixel that got the following scores during the template matching for 10 different orientations:

```
>>> x
array([0.89265841, 0.95905692, 0.46393858, 0.85648408, 0.28807063,
       0.66441311, 0.51129509, 0.59213952, 0.95905692, 0.91623368])
```

The annotated score for this pixel will be `max(x) = 0.95905692` which occurs for two orientations, namely at index 1 and 8. As currently the score and index of a pixel are only updated if a higher correlation is found, the orientation index of this pixel will be 1.

Now lets say the orientation search is split over two gpus, we will get the following scores for this same pixel in search 1

```
>>> x[slice(0, 10, 2)]
array([0.89265841, 0.46393858, 0.28807063, 0.51129509, 0.95905692])
```

and search 2

```
>>> x[slice(1, 10, 2)]
array([0.95905692, 0.85648408, 0.66441311, 0.59213952, 0.91623368])
```

This mean search 1 has the max score at orientation index 8, and search 2 the max score at orientation index 1. However, this full list of scores for each pixel is of course not stored (as that is not possible in memory), rather only the max of each search is stored. 

Now, this results in the max of search 1 occuring first, although this is now the orientation at index 8 instead of index 1.

Why I have never gotten this error when running the tests on multiple machines is strange however...

**Comment by McHaillet** [comment]
Alternative solution could be to not split the rotation search with `slice(star, n_rotations, n_jobs)` but with something like `[job_id * (n_rotations // n_jobs): (job_id + 1) * (n_rotations // n_jobs)]`

**Comment by McHaillet** [comment]
@YunjieChang, @junhe123,

We pushed an update for this issue, see latest commit [956644f](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/commit/956644f41fe25b87816ac30ab384d07b1a2e79ed). Could you install this update and see if the unittests now complete for you without fails?

**Comment by YunjieChang** [comment]
Hi McHaillet,

I updated to v0.3.2, but still got the error message with the unittests:
<img width="1000" alt="Screenshot 2023-11-11 at 19 11 35" src="https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/54540487/c589f4b8-1112-4575-b724-711dce09a9a8">

**Comment by McHaillet** [comment]
It is a bit strange to me that the errors you get are slightly different each time. To sum up in each image I see the following errors:

1) In version 0.3.0 test_parallel_manager and test_tm_job_split_volume both had the same angle id difference of 53.0
2) In version 0.3.1 test_tm_job_split_angles produced the wrong results
3) In version 0.3.2 test_parallel_manager and test_tm_job_split_volume both had the same angle id difference of 104.0

That test_parallel_manager and test_tm_job_split give the same error makes sense as in both cases the input is split into subvolumes. So its good that those are consistent with each other.

But the difference is test errors between 0.3.1 and 0.3.2 seems very unlikely to me.

If you run the unittests multiple times, do you each time get identical errors or are there tiny differences? For example is the 104. value the same each time you run the test?

**Comment by sroet** [comment]
@YunjieChang We found a way of reproducing the issue on our systems, will keep you posted about any updates :smile:

**Comment by McHaillet** [comment]
@YunjieChang We managed to fix the issue. As it was exactly the same problem on our system I expect it is solved for you as well. Would you still be so kind to pull the latest version and confirm that it is solved for you as well?

**Comment by YunjieChang** [comment]
Hi McHaillet,

Haven't checked the github emails for several days. I just updated to the latest version and it works perfectly.

Thanks!
Yunjie

**Comment by McHaillet** [comment]
Perfect, thanks for checking!
