### ISSUE TITLE
ERROR: test_parallel_manager (test_tmjob.TestTMJob.test_parallel_manager)

### ISSUE THREAD

**Issue by chris-hypercag** [SBC-Utrecht/pytom-template-matching-gpu#74]
Hello developers,

I was able to install the software successfully per the README instructions. However when I ran the unittest I encountered an error with `test_parallel_manager`. The error is similar to issue [#58](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/issues/58) and [#66](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/pull/66), except that the traceback for the error is different. 

```
======================================================================
ERROR: test_parallel_manager (test_tmjob.TestTMJob.test_parallel_manager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../pytom-template-matching-gpu/tests/test_tmjob.py", line 262, in test_parallel_manager
    score, angle = run_job_parallel(self.job, volume_splits=(1, 3, 1), gpu_ids=[0])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../anaconda3/envs/pytom_tm/lib/python3.12/site-packages/pytom_tm/parallel.py", line 96, in run_job_parallel
    raise RuntimeError('One of the processes stopped unexpectedly.')
RuntimeError: One of the processes stopped unexpectedly.

----------------------------------------------------------------------
```

I am running the software on a large heterogeneous cluster, and ran into the error when executing the test with a Nvidia Tesla V100-SXM2, and Tesla P40. The error did not occur when running on an Nvidia A30.  All three of these GPU's are currently supporting CUDA version 12.3 with driver version 545.23.08. 

In all three cases running `python -c "import cupy as cp; a = cp.zeros((100,100)); print(a)"` produced the correct output, so I told the user they can probably use the software, just to be wary of the results. I've attached the entire test output; it contains more information than the excerpt above. Please, let me know if you need anymore info.

Cheers,
Chris

[github_issue_report.txt](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/files/13845310/github_issue_report.txt)

**Comment by McHaillet** [comment]
Hi Chris,

Thanks for the detailed report. Your issue seems different from #58 and #66 as those had a numerical incosistency in the tests. In your case it seems rather that the test broke because at one point the GPU was unavailable (line 33 in your attached file):

```cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorDevicesUnavailable: CUDA-capable device(s) is/are busy or unavailable```

Judging from this, it could be that another program was using the GPU simultaneously during the tests.

Would you mind running the tests a couple of times to see if the error is consistent in each run?

Best wishes,
Marten

**Comment by chris-hypercag** [comment]
Hello Marten,

Thank you for your quick response, it's very much appreciated.

I ran the test several more times and the error is consistent. I re-ran the test 10 times on the Tesla V100, twice on the Tesla P40, and twice on a RTX2080. Each of these tests were run on a cluster using Slurm resource manager, so in each instance the test had exclusive access to the gpu's allocated to it, which only makes the `cudaErrorDevicesUnavailable` error more mysterious and less helpful.

As for running on the A30_MIG, I've run the test maybe 6+ times, each time the test completed successfully. The only difference between these tests and the others is they were performed on our interactive nodes. 

I don't know what the test consists of, but is it possible that the part of the test is performing a blocking operation while trying to run another part concurrently? It may explain why the A30_MIG is able to perform the test correctly because the MIG architecture partitions the GPU. Either way thank you for your help.

Best regards,
Chris

**Comment by sroet** [comment]
Hey Chris,
Thanks for rerunning the tests, very much appreciated

I have a bit of a suspicion where this might come from, do you by any chance know what the compute mode is of your GPUs? 
(I suspect the failing ones are in `exclusive process` mode, instead of `default`)
You can see this by running `nvidia-smi` and looking at the highlighted part:
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/19587267/304b06cb-19a4-47da-8ac2-019ec42f95aa) 
or your cluster system administrators should be able to tell you.

**Comment by chris-hypercag** [comment]
Hello Sander,

Your suspicions were correct! The three GPU's that prevented the test from completing were running in `exclusive process` mode and the interactive GPU was running in `default` mode.  When I added `#SBATCH --gpu_cmode=shared` to my batch script the test completed correctly. 

Thank you for being proactive in resolving issues!

Best regards,
Chris
